# Generated by Django 3.1.5 on 2021-12-23 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.TextField(verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Имя заказчика')),
                ('surname', models.TextField(verbose_name='Фамилия заказчика')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.TextField(verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Название предмета')),
                ('description', models.TextField(verbose_name='Описание предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Имя сотрудника')),
                ('full_name', models.TextField(verbose_name='ФИО')),
                ('sex', models.CharField(choices=[('м', 'Мужской'), ('ж', 'Женский')], max_length=1, verbose_name='Пол')),
                ('position', models.CharField(choices=[('Бухгалтер', 'Бухгалтер'), ('Администратор', 'Администратор'), ('Менеджер', 'Менеджер')], max_length=20, verbose_name='Должность')),
                ('photo', models.TextField(verbose_name='Фотография')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Имя студента')),
                ('surname', models.TextField(verbose_name='Фамилия студента')),
                ('status', models.CharField(choices=[('y', 'Учится'), ('n', 'Отчсилен'), ('q', 'Зачислен'), ('a', 'Решается')], max_length=1)),
                ('course', models.IntegerField(verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Имя заказчика')),
                ('surname', models.TextField(verbose_name='Фамилия заказчика')),
                ('experience', models.IntegerField(verbose_name='Опыт (лет)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lessons')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='TeachersPhotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(verbose_name='Ссылка на фотографию')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teachers')),
            ],
            options={
                'verbose_name': 'Фото преподавателя',
                'verbose_name_plural': 'Фото преподавателей',
            },
        ),
        migrations.CreateModel(
            name='StudentsProjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projects')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students')),
            ],
            options={
                'verbose_name': 'Проект студента',
                'verbose_name_plural': 'Проекты студентов',
            },
        ),
        migrations.CreateModel(
            name='StudentsPhoto',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(verbose_name='Ссылка на фото')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.students')),
            ],
            options={
                'verbose_name': 'Фото студента',
                'verbose_name_plural': 'Фото студентов',
            },
        ),
        migrations.CreateModel(
            name='StudentsLessons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lessons')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students')),
            ],
            options={
                'verbose_name': 'Предмет студента',
                'verbose_name_plural': 'Предметы студентов',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Имя организации')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='main.city')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='EngineerProjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Название инженерного проекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clients')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students')),
            ],
            options={
                'verbose_name': 'Инженерный проетк',
                'verbose_name_plural': 'Инженерные проеткы',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countryes', to='main.country'),
        ),
    ]
