# Generated by Django 3.1.5 on 2021-12-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агенты',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('sex', models.CharField(choices=[('м', 'Мужской'), ('ж', 'Женский')], max_length=1, verbose_name='Пол')),
                ('photo', models.CharField(max_length=255, verbose_name='Фотография')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('birthplace', models.CharField(max_length=255, verbose_name='Место рождения')),
                ('passport_series', models.IntegerField(verbose_name='Серия паспорта')),
                ('passport_number', models.IntegerField(verbose_name='Номер паспорта')),
                ('passport_date', models.DateField(verbose_name='Дата выдачи')),
                ('passport_date_end', models.DateField(verbose_name='Дата окончания действия')),
                ('agency', models.CharField(max_length=255, verbose_name='Орган выдавший документ')),
                ('status', models.CharField(choices=[('Привелигированный', 'Привелигированный'), ('Обычный', 'Обычный'), ('VIP', 'VIP')], max_length=25)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participants', models.IntegerField(verbose_name='Участники поездки')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total', models.FloatField(verbose_name='Сумма(в валюте)')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название отеля')),
                ('category', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('a', 'Апартаменты')], max_length=1)),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя организации')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='main.city')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contract')),
            ],
            options={
                'verbose_name': 'Маршрут поездки',
                'verbose_name_plural': 'Маршруты поездок',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transport', models.CharField(max_length=255, verbose_name='Вид транспорта')),
            ],
            options={
                'verbose_name': 'Ваучер',
                'verbose_name_plural': 'Ваучеры',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival', models.TimeField(verbose_name='Дата прибытия')),
                ('departure', models.TimeField(verbose_name='Дата отправления')),
                ('car_model', models.CharField(max_length=100, verbose_name='Модель машины')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voucher')),
            ],
            options={
                'verbose_name': 'Модель машины',
                'verbose_name_plural': 'Модели машин',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_number', models.CharField(choices=[('Стандарт', 'Стандарт'), ('Делюкс', 'Делюкс')], max_length=15, verbose_name='Тип номера')),
                ('type_of_eat', models.CharField(choices=[('RO', 'RO'), ('EP', 'EP'), ('BB', 'BB'), ('H', 'H')], max_length=15, verbose_name='Тип питания')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hotels')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.route')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voucher')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя сотрудника')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('sex', models.CharField(choices=[('м', 'Мужской'), ('ж', 'Женский')], max_length=1, verbose_name='Пол')),
                ('position', models.CharField(choices=[('Бухгалтер', 'Бухгалтер'), ('Администратор', 'Администратор'), ('Менеджер', 'Менеджер')], max_length=20, verbose_name='Должность')),
                ('photo', models.CharField(max_length=255, verbose_name='Фотография')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organisation')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_currency', models.FloatField(verbose_name='Сумма(в валюте)')),
                ('total_rubles', models.FloatField(verbose_name='Сумма(в рублях)')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contract')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='PaymentOfTheContract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('total', models.FloatField(verbose_name='Сумма(в валюте)')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contract')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
            options={
                'verbose_name': 'Оплата договора',
                'verbose_name_plural': 'Оплата договоров',
            },
        ),
        migrations.CreateModel(
            name='ParticipantsOfTheTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contract')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voucher')),
            ],
            options={
                'verbose_name': 'Участники поездки',
                'verbose_name_plural': 'Участники поездок',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organisation'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countryes', to='main.country'),
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата соглашения')),
                ('date_begin', models.DateField(verbose_name='Дата начала поездки')),
                ('date_end', models.DateField(verbose_name='Дата окончания поездки')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agents')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('countryes', models.ManyToManyField(to='main.Country')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organisation')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
            options={
                'verbose_name': 'Соглашение',
                'verbose_name_plural': 'Соглашения',
            },
        ),
        migrations.AddField(
            model_name='agents',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='main.organisation'),
        ),
    ]
