# Generated by Django 3.1.5 on 2021-12-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Имя')),
                ('full_name', models.TextField(verbose_name='ФИО')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='main.organisation')),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агенты',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participants', models.IntegerField(verbose_name='Участники поездки')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total', models.FloatField(verbose_name='Сумма(в валюте)')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organisation')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='PaymentOfTheContract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('total', models.FloatField(verbose_name='Сумма(в валюте)')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contract')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
            options={
                'verbose_name': 'Оплата договора',
                'verbose_name_plural': 'Оплата договоров',
            },
        ),
        migrations.RemoveField(
            model_name='engineerprojects',
            name='client',
        ),
        migrations.RemoveField(
            model_name='engineerprojects',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentslessons',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='studentslessons',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentsphoto',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='studentsprojects',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='studentsprojects',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='teachersphotos',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='EngineerProjects',
        ),
        migrations.DeleteModel(
            name='Lessons',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='StudentsLessons',
        ),
        migrations.DeleteModel(
            name='StudentsPhoto',
        ),
        migrations.DeleteModel(
            name='StudentsProjects',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.DeleteModel(
            name='TeachersPhotos',
        ),
    ]
