# Generated by Django 3.1.5 on 2021-12-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_staff_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='currency',
            field=models.CharField(default=1, max_length=100, verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
