# Generated by Django 3.1.5 on 2021-12-23 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата соглашения')),
                ('date_begin', models.DateField(verbose_name='Дата начала поездки')),
                ('date_end', models.DateField(verbose_name='Дата окончания поездки')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agents')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('countryes', models.ManyToManyField(to='main.Country')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organisation')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
            options={
                'verbose_name': 'Соглашение',
                'verbose_name_plural': 'Соглашения',
            },
        ),
    ]
