# Generated by Django 3.1.5 on 2021-12-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_report_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название договора'),
            preserve_default=False,
        ),
    ]
