# Generated by Django 3.1.5 on 2021-12-23 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contract')),
            ],
            options={
                'verbose_name': 'Маршрут поездки',
                'verbose_name_plural': 'Маршруты поездок',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transport', models.TextField(verbose_name='Вид транспорта')),
            ],
            options={
                'verbose_name': 'Ваучер',
                'verbose_name_plural': 'Ваучеры',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_number', models.CharField(choices=[('Стандарт', 'Стандарт'), ('Делюкс', 'Делюкс')], max_length=15)),
                ('type_of_eat', models.CharField(choices=[('RO', 'RO'), ('EP', 'EP'), ('BB', 'BB'), ('H', 'H')], max_length=15)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hotels')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.route')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voucher')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
