# Generated by Django 3.1.5 on 2021-12-23 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_route_tour_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='agents',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='client',
            name='agency',
            field=models.CharField(max_length=255, verbose_name='Орган выдавший документ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthplace',
            field=models.CharField(max_length=255, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.CharField(max_length=255, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='adress',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название отеля'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя организации'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.CharField(max_length=255, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type_of_eat',
            field=models.CharField(choices=[('RO', 'RO'), ('EP', 'EP'), ('BB', 'BB'), ('H', 'H')], max_length=15, verbose_name='Тип питания'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type_of_number',
            field=models.CharField(choices=[('Стандарт', 'Стандарт'), ('Делюкс', 'Делюкс')], max_length=15, verbose_name='Тип номера'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='transport',
            field=models.CharField(max_length=255, verbose_name='Вид транспорта'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival', models.TimeField(verbose_name='Дата прибытия')),
                ('departure', models.TimeField(verbose_name='Дата отправления')),
                ('car_model', models.CharField(max_length=100, verbose_name='Модель машины')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voucher')),
            ],
            options={
                'verbose_name': 'Модель машины',
                'verbose_name_plural': 'Модели машин',
            },
        ),
        migrations.CreateModel(
            name='ParticipantsOfTheTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contract')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voucher')),
            ],
            options={
                'verbose_name': 'Участники поездки',
                'verbose_name_plural': 'Участники поездок',
            },
        ),
    ]
